PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6

PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"

PROJECT_STATUS_CHOICES = (
    (PROJECT_STATUS_OPEN, "Открыт"),
    (PROJECT_STATUS_CLOSED, "Закрыт"),
)

GITHUB_URL_MAX_LENGTH = 200
GITHUB_ALLOWED_HOSTS = ("github.com", "www.github.com")

PROJECTS_PER_PAGE = 12
USERS_PER_PAGE = 12

USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

PHONE_PATTERN = r"^(8\d{10}|\+7\d{10})$"

SKILL_NAME_MAX_LENGTH = 124
SKILLS_SUGGESTIONS_LIMIT = 10

AVATAR_UPLOAD_TO = "avatars/"
AVATAR_IMAGE_SIZE = 256
AVATAR_FONT_SIZE = 120
AVATAR_TEXT_VERTICAL_OFFSET = 10
AVATAR_TEXT_COLOR = "white"
AVATAR_IMAGE_MODE = "RGB"
AVATAR_IMAGE_FORMAT = "PNG"
AVATAR_IMAGE_EXTENSION = "png"
AVATAR_GENERATED_PREFIX = "generated"
AVATAR_FILE_HASH_LENGTH = 16

AVATAR_FONT_NAME = "arial.ttf"
AVATAR_FALLBACK_FONT_NAME = "DejaVuSans-Bold.ttf"

AVATAR_COLOR_BLUE_GRAY = "#6D8EA0"
AVATAR_COLOR_GREEN = "#7A9E7E"
AVATAR_COLOR_BROWN = "#B08968"
AVATAR_COLOR_PURPLE = "#8E7DBE"
AVATAR_COLOR_BLUE = "#6096BA"
AVATAR_COLOR_SAND = "#A98467"

AVATAR_BACKGROUND_COLORS = (
    AVATAR_COLOR_BLUE_GRAY,
    AVATAR_COLOR_GREEN,
    AVATAR_COLOR_BROWN,
    AVATAR_COLOR_PURPLE,
    AVATAR_COLOR_BLUE,
    AVATAR_COLOR_SAND,
)
