# Generated by Django 5.2.4 on 2026-05-27 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=150)),
                ('project_description', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.CharField(choices=[('OPEN', 'Open for participants'), ('CLOSED', 'Closed / Finished')], default='OPEN', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_created_projects', to=settings.AUTH_USER_MODEL)),
                ('joined_members', models.ManyToManyField(blank=True, related_name='participating_in', to=settings.AUTH_USER_MODEL)),
                ('required_skills', models.ManyToManyField(blank=True, related_name='projects_with_this_skill', to='skills_app.projectskill')),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
    ]
